<div class="title"><h1>Baner na start</h1></div>
<div class="row-fluid">
	<div class="span12">
		<ul class="nav nav-tabs none">
			<li><a href="<?=$this->baseUrl();?>/admin/ustawienia/"><span class="fa i-cog"></span>Główne ustawienia strony</a></li>
			<li><a href="<?=$this->baseUrl();?>/admin/ustawienia/social/"><span class="fa i-lista"></span>Portale społecznościowe</a></li>
			<li><a href="<?=$this->baseUrl();?>/admin/ustawienia/mapa/"><span class="fa i-map"></span>Kontakt</a></li>
			<li><a href="<?=$this->baseUrl();?>/admin/ustawienia/backup/"><span class="fa i-sql"></span>Kopia bazy</a></li>
			<li class="active"><a href="<?=$this->baseUrl();?>/admin/ustawienia/baner/"><span class="fa i-image"></span>Baner na start</a></li>
		</ul>
		<div class="widget">
		<div class="tab-content">
			<?php echo $this->info ;?>
			<?php echo $this->form ;?>
		</div>
		</div>
	</div>
</div>

<script type="text/javascript">
    $(document).ready(function() { tinymce(); });
    <?php if(($this->message == 1)) {?>
    const noty_id = noty({timeout: 3000, text: 'Zapisano!', type: 'success'});
    <?php } ?>
    <?php if(($this->message == 2)) {?>
    const noty_id = noty({timeout: 3000, text: 'Błąd w formularzu', type: 'error'});
    <?php } ?>
</script>