<!doctype html>
<html lang="pl">
<head>
	<meta charset="utf-8">
	<title>kCMS - Logowanie</title>
	<meta name="description" content="">
	<meta name="keywords" content="">
	<meta name="author" content="Jacek Kurowski">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, user-scalable=no">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,600,700&amp;subset=latin,latin-ext" type="text/css">
	<meta name="robots" content="noindex, nofollow">

	<!-- Style -->
    <link rel="stylesheet" href="<?=$this->adminCssUrl();?>/admin.css?v=1">

	<!-- jQuery -->
    <script src="<?=$this->jsUrl();?>/jquery.js" charset="utf-8"></script>
	<script src="<?=$this->jsUrl();?>/validation.js" charset="utf-8"></script>
	<script src="<?=$this->jsUrl();?>/pl.js" charset="utf-8"></script>
    <script src="<?=$this->jsUrl();?>/cms.js" charset="utf-8"></script>

	</head>
	<body id="logowanie">
		<?=$this->layout()->content; ?>
	</body>
</html>