<footer>
    <div class="container">
        <div class="row">
            <div class="col-3 pt-5">
                <p class="mt-4">Dr Fish <?=date('Y');?></p>
            </div>
            <div class="col-6">
                <div id="flogo">
                    <img src="<?=$this->gfxUrl();?>/logo_dr_fisz_poziom.png" alt="Dr Fish">
                </div>
            </div>
            <div class="col-3 text-right pt-5">
                <p class="mt-4">Realizacja: <a href="#" target="_blank">JK Design</a></p>
            </div>
        </div>
    </div>
</footer>

<div id="cookies"><p><a href="" class="closecookies gradient">Zamknij</a><?= $this->header->cookies; ?></p></div>

<!-- Google Fonts -->
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">