<footer>
    <div class="container">
        <div class="row">
            <div class="col-6 col-sm-4 col-sm-3 pt-3 pt-sm-5">
                <p class="mt-0 mt-sm-4">Dr Fish <?=date('Y');?></p>
            </div>
            <div class="col-6 col-sm-4 col-sm-6">
                <div id="flogo">
                    <img src="<?=$this->gfxUrl();?>/logo_dr_fisz_poziom.png" alt="Dr Fish">
                </div>
            </div>
            <div class="col-12 col-sm-4 col-sm-3 text-center text-sm-right pb-3 pb-sm-0 pt-0 pt-sm-5">
                <p class="mt-0 mt-sm-4">Realizacja: <a href="#" target="_blank">JK Design</a></p>
            </div>
        </div>
    </div>
</footer>

<div id="cookies"><p><a href="" class="closecookies gradient">Zamknij</a><?= $this->header->cookies; ?></p></div>

<!-- Google Fonts -->
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">